// GENERATED by extract_board.py -- do not edit.
// source: VANDIMMER-4CH2A.kicad_pcb
// revision: git tag ordered-revA
//
// Board coordinates: origin at the outline's top-left corner as KiCad draws it,
// x right, y DOWN. case.scad converts y with by().

pcb_w = 100.050;
pcb_h = 84.050;
pcb_t = 1.6;

// [x, y, drill] per mounting hole
pcb_holes = [
  [4.525, 8.525, 3.200],
  [4.525, 79.525, 3.200],
  [95.525, 8.525, 3.200],
  [95.525, 79.525, 3.200],
];

// [name, role, x0, x1, y0, y1, cx, cy, height_above_board]
pcb_parts = [
  ["J11", "button", 1.730, 5.320, 61.730, 67.870, 3.525, 63.525, 8.55],  // measured from 3D model
  ["J12", "button", 1.730, 5.320, 68.830, 74.970, 3.525, 70.625, 8.55],  // measured from 3D model
  ["J13", "debug_header", 54.230, 57.820, 37.230, 53.520, 56.025, 39.025, 8.55],  // measured from 3D model
  ["J14", "debug_header", 6.230, 17.440, 42.230, 45.820, 8.025, 44.025, 8.55],  // measured from 3D model
  ["Q1", "fets", 6.610, 17.760, 61.355, 68.550, 13.025, 65.025, 2.33],  // measured from 3D model
  ["Q4", "fets", 40.510, 51.660, 61.355, 68.550, 46.925, 65.025, 2.33],  // measured from 3D model
  ["J3", "harness", 8.050, 16.500, 70.690, 83.250, 11.025, 73.525, 6.11],  // measured from 3D model
  ["J4", "harness", 19.050, 27.500, 70.690, 83.250, 22.025, 73.525, 6.11],  // measured from 3D model
  ["J5", "harness", 30.050, 38.500, 70.690, 83.250, 33.025, 73.525, 6.11],  // measured from 3D model
  ["J6", "harness", 41.050, 49.500, 70.690, 83.250, 44.025, 73.525, 6.11],  // measured from 3D model
  ["J7", "harness", 53.050, 66.500, 70.690, 83.250, 56.025, 73.525, 6.11],  // measured from 3D model
  ["J8", "harness", 69.050, 82.500, 70.690, 83.250, 72.025, 73.525, 6.11],  // measured from 3D model
  ["L1", "hot", 81.575, 90.000, 14.675, 21.375, 86.025, 18.025, 3.00],  // assumed: cjiang FXL0630, 6.6 x 7.0 x 3.0 mm
  ["L3", "hot", 53.575, 62.000, 7.175, 13.875, 58.025, 10.525, 3.00],  // assumed: cjiang FXL0630, 6.6 x 7.0 x 3.0 mm
  ["U2", "hot", 73.950, 78.100, 16.125, 19.750, 76.025, 18.025, 1.10],  // assumed: TSOT-23-6 body
  ["J10", "jumper", 92.230, 95.820, 52.230, 60.900, 94.025, 54.025, 8.55],  // measured from 3D model
  ["J9", "jumper", 92.230, 95.820, 42.230, 50.900, 94.025, 44.025, 8.55],  // measured from 3D model
  ["D7", "led", 81.465, 88.585, 53.215, 58.835, 85.025, 56.025, 1.61],  // measured from 3D model
  ["U1", "module", 30.150, 50.350, 33.750, 53.300, 40.025, 43.525, 3.20],  // assumed: ESP32-S3-WROOM-1U module incl. shield
  ["J2", "power_edge", 9.870, 21.200, 4.500, 15.685, 18.025, 13.025, 7.56],  // measured from 3D model
  ["J1", "usb_edge", -0.500, 8.970, 50.680, 61.370, 3.675, 56.025, 3.30],  // assumed: USB-C receptacle body, HRO TYPE-C-31-M-12 datasheet
];

// Helpers over pcb_parts
function part_row(ref) = pcb_parts[search([ref], pcb_parts)[0]];
function parts_with(role) = [for (p = pcb_parts) if (p[1] == role) p];
function role_x0(role) = min([for (p = parts_with(role)) p[2]]);
function role_x1(role) = max([for (p = parts_with(role)) p[3]]);
function role_y0(role) = min([for (p = parts_with(role)) p[4]]);
function role_y1(role) = max([for (p = parts_with(role)) p[5]]);
function role_h(role)  = max([for (p = parts_with(role)) p[8]]);
function all_parts_h() = max([for (p = pcb_parts) p[8]]);

